### ISSUE TITLE
Create JSON Files for Questions

### ISSUE THREAD

**Issue by PranavGitHubAcc** [PranavGitHubAcc/Techeshi-Castle#15]
Tasks:
	•	Use Gemini to create a file for General Knowledge Questions.
	•	Ensure the file is an array of JSON objects.
	•	Verify the object structure:
```
{
  "question": "What is the capital of France?",
  "options": [
    "Berlin",
    "London",
    "Paris",
    "Rome"
  ],
  "answer": "Paris"
}
```
•	Use Gemini to create a file for Simple Coding Questions.
•	Ensure the file follows the same structure as above.

**Comment by CholexMax** [comment]
[
  {
    "question": "What is a variable in programming?",
    "options": [
      "A constant value",
      "A container for storing data",
      "A type of function",
      "An operator"
    ],
    "answer": "A container for storing data"
  },
  {
    "question": "What does CSS stand for?",
    "options": [
      "Cascading Style Sheets",
      "Computer Style Sheets",
      "Creative Style System",
      "Coded Style Syntax"
    ],
    "answer": "Cascading Style Sheets"
  },
  {
    "question": "Which symbol is used for single-line comments in JavaScript?",
    "options": [
      "//",
      "/*",
      "--",
      "#"
    ],
    "answer": "//"
  },
  {
    "question": "What is the purpose of the 'if' statement in programming?",
    "options": [
      "To declare a variable",
      "To perform a loop",
      "To execute code conditionally",
      "To define a function"
    ],
    "answer": "To execute code conditionally"
  },
  {
    "question": "What does the 'return' statement do in a function?",
    "options": [
      "Stops the function",
      "Returns a value from the function",
      "Loops the function",
      "Declares a variable"
    ],
    "answer": "Returns a value from the function"
  },
  {
    "question": "What is an array in programming?",
    "options": [
      "A single value",
      "A collection of values",
      "A mathematical function",
      "A loop structure"
    ],
    "answer": "A collection of values"
  },
  {
    "question": "What does HTTP stand for?",
    "options": [
      "HyperText Transfer Protocol",
      "HighText Transfer Protocol",
      "HyperText Transmission Protocol",
      "Hyper Transfer Text Protocol"
    ],
    "answer": "HyperText Transfer Protocol"
  },
  {
    "question": "Which HTML tag is used to create a hyperlink?",
    "options": [
      "<link>",
      "<a>",
      "<href>",
      "<url>"
    ],
    "answer": "<a>"
  },
  {
    "question": "What is the main purpose of JavaScript?",
    "options": [
      "To style web pages",
      "To structure web pages",
      "To add interactivity to web pages",
      "To manage databases"
    ],
    "answer": "To add interactivity to web pages"
  },
  {
    "question": "What does API stand for?",
    "options": [
      "Application Programming Interface",
      "Advanced Programming Interface",
      "Application Process Interface",
      "Automated Programming Interface"
    ],
    "answer": "Application Programming Interface"
  },
  {
    "question": "What is the purpose of the 'for' loop in programming?",
    "options": [
      "To define a variable",
      "To execute a block of code multiple times",
      "To stop the code",
      "To declare a function"
    ],
    "answer": "To execute a block of code multiple times"
  },
  {
    "question": "What is the function of the 'console.log' command in JavaScript?",
    "options": [
      "To log messages to the console",
      "To declare a variable",
      "To create a loop",
      "To style the page"
    ],
    "answer": "To log messages to the console"
  },
  {
    "question": "Which operator is used for strict equality in JavaScript?",
    "options": [
      "==",
      "=",
      "===",
      "!=="
    ],
    "answer": "==="
  },
  {
    "question": "What does JSON stand for?",
    "options": [
      "JavaScript Object Notation",
      "Java Standard Output Network",
      "Java Serialized Object Notation",
      "Java Syntax Object Node"
    ],
    "answer": "JavaScript Object Notation"
  },
  {
    "question": "Which keyword is used to declare a constant variable in JavaScript?",
    "options": [
      "var",
      "let",
      "const",
      "static"
    ],
    "answer": "const"
  }
]

CAN IT WORKS AS YOU NEED

**Comment by PranavGitHubAcc** [comment]
@CholexMax Yes this works. Thank You.
