### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by onkar69483** [PranavGitHubAcc/Techeshi-Castle#8]
**Purpose:** Admin-only page for managing teams and challenges.
**Access:**
    - Accessible only via URL (no direct link on the landing page).
    - Admin login required to access the page.
**Features:**
    - Redirect to **Dashboard Page** after successful admin login.
    - Option to **"Create Team"** (redirects to the **Create Page**).
    - Leaderboard displaying teams in the order of their creation.
    - Search bar to filter teams by name or ID.
    - Edit functionality to update team information, including names and points for all challenges.

**Comment by SachinMhetre678** [comment]
## 1. Authentication System
- **Admin Login Page:**
  - Added a custom login form with fields for username and password.
  - Implemented error handling for invalid credentials.
  - Mock authentication setup (username: `admin`, password: `admin123`).
  - Secure routing with protected routes.
  - Session management using `localStorage` for storing authentication state.

## 2. Protected Routes
- **Route Protection:**
  - Implemented authentication state checking to restrict access to protected routes.
  - Unauthorized users are automatically redirected to the login page.
  - Protected routes include the admin dashboard and team creation sections.

## 3. Admin Dashboard
- **Team Management:**
  - Designed a table view for all teams with real-time search functionality.
  - Enabled editing of team details:
    - Team name.
    - Challenge scores (1-3).
    - Completion time.
    - Total points automatically calculated based on scores.
  - Added delete functionality to remove teams.
  - Provided the option to create new teams directly from the dashboard.

## 4. Team Creation
- **Create Team Form:**
  - Developed a form to create new teams with the following features:
    - Input for team name.
    - Automatic ID generation for each team.
    - Initial state setup with zero points for all challenges and a default completion time of `0:00:00`.
    - Form validation to ensure correct inputs.
    - Redirect to the appropriate page after successful team creation.

## 5. Leaderboard Features
- **Live Updates:**
  - Integrated real-time score updates with automatic sorting based on total points.
  - Implemented a 5-second refresh interval for dynamic leaderboard updates.
  - Animated transitions for smoother updates.
  - Designed a responsive layout with highlighted top 3 teams, rank icons, and avatars.

## 6. Data Management
- **Local Storage:**
  - Used `localStorage` to ensure persistent data storage for teams.
  - Data structure includes:
    - Unique ID.
    - Team name.
    - Individual challenge scores.
    - Total points.
    - Completion time.
  - Real-time updates to data on edit or create operations.
  - Added validation to ensure the integrity of stored data.

## 7. User Interface
- **Design Elements:**
  - Created a responsive layout with gaming-themed styling.
  - Incorporated gradient effects and custom fonts (`Space Grotesk`, `Orbitron`).
  - Added interactive UI elements with loading states, error messages, and success notifications for a better user experience.

## 8. Navigation
- **Routing System:**
  - Configured routing for:
    - Home page.
    - Events page.
    - Admin dashboard.
    - Leaderboard.
    - Team creation.
  - Ensured protected routes for sensitive sections of the application.

**Comment by onkar69483** [comment]
@SachinMhetre678 let's close this issue once the backend is integrated on dashboard page
